project_id = "mtzoavtbtqflufyccern"

[functions.generate-oauth-state]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.get-user-meta-accounts]
verify_jwt = false

[functions.disconnect-meta]
verify_jwt = false

[functions.sync-meta-campaigns]
verify_jwt = false

[functions.get-audience-insights]
verify_jwt = false

[functions.manage-leadads-subscription]
verify_jwt = false

[functions.meta-campaigns-manager]
verify_jwt = false

[functions.meta-alerts-evaluator]
verify_jwt = false

[functions.typeform-manager]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[functions.zapsign-webhook]
verify_jwt = false
