import {
  Aggregation,
  ChartType,
  DataSource,
  DateGrouping,
  FormatType,
} from "./types";

/**
 * Receitas prontas em linguagem do dia a dia.
 * O usuário escolhe uma pergunta ("Quanto cada vendedor vendeu?") e o Studio
 * preenche fonte, medida, agrupamento, formato e tipo de gráfico sozinho.
 */
export interface VisualRecipe {
  id: string;
  /** Pergunta que o usuário quer responder */
  question: string;
  /** Explicação de uma linha */
  hint: string;
  emoji: string;
  group: 'Vendas' | 'Metas' | 'Time' | 'Atividades' | 'Leads' | 'WhatsApp';
  title: string;
  chartType: ChartType;
  dataSource: DataSource;
  measureField: string | null;
  aggregation: Aggregation;
  dimensionField: string | null;
  dateGrouping?: DateGrouping;
  formatType: FormatType;
  statusFilter?: 'won' | 'lost' | 'open';
}

export const VISUAL_RECIPES: VisualRecipe[] = [
  {
    id: 'faturamento_por_vendedor',
    question: 'Quanto cada vendedor vendeu?',
    hint: 'Ranking de faturamento dos negócios ganhos',
    emoji: '🏆',
    group: 'Vendas',
    title: 'Faturamento por vendedor',
    chartType: 'ranking',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'responsible_name',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'faturamento_por_mes',
    question: 'Como está o faturamento mês a mês?',
    hint: 'Evolução das vendas ganhas ao longo do tempo',
    emoji: '📈',
    group: 'Vendas',
    title: 'Faturamento por mês',
    chartType: 'bar',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'won_at',
    dateGrouping: 'month',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'faturamento_total',
    question: 'Qual o total vendido no período?',
    hint: 'Um número grande, direto na tela',
    emoji: '💰',
    group: 'Vendas',
    title: 'Faturamento total',
    chartType: 'scorecard',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'won_at',
    dateGrouping: 'month',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'faturamento_por_canal',
    question: 'Qual canal traz mais dinheiro?',
    hint: 'Faturamento ganho separado por canal de entrada',
    emoji: '📣',
    group: 'Vendas',
    title: 'Faturamento por canal',
    chartType: 'bar_horizontal',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'canal',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'vendas_por_produto',
    question: 'Qual produto vende mais?',
    hint: 'Faturamento ganho separado por produto',
    emoji: '📦',
    group: 'Vendas',
    title: 'Faturamento por produto',
    chartType: 'bar_horizontal',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'product',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'funil_etapas',
    question: 'Quantos negócios tem em cada etapa?',
    hint: 'Funil do pipeline por etapa',
    emoji: '🫗',
    group: 'Vendas',
    title: 'Negócios por etapa',
    chartType: 'funnel',
    dataSource: 'deals',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'stage_name',
    formatType: 'decimal',
  },
  {
    id: 'motivos_perda',
    question: 'Por que estamos perdendo negócios?',
    hint: 'Contagem de negócios perdidos por motivo',
    emoji: '❌',
    group: 'Vendas',
    title: 'Motivos de perda',
    chartType: 'bar_horizontal',
    dataSource: 'deals',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'lost_reason',
    formatType: 'decimal',
    statusFilter: 'lost',
  },
  {
    id: 'negocios_por_vendedor',
    question: 'Quantos negócios cada vendedor tem?',
    hint: 'Contagem de negócios por responsável',
    emoji: '👥',
    group: 'Time',
    title: 'Negócios por vendedor',
    chartType: 'ranking',
    dataSource: 'deals',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'responsible_name',
    formatType: 'decimal',
  },
  {
    id: 'calls_comerciais',
    question: 'Como está a agenda de calls do time?',
    hint: 'Painel pronto de calls agendadas x concluídas',
    emoji: '📞',
    group: 'Time',
    title: 'Calls comerciais',
    chartType: 'call_commercial',
    dataSource: 'tasks',
    measureField: null,
    aggregation: 'count',
    dimensionField: null,
    formatType: 'decimal',
  },
  {
    id: 'atividades_por_pessoa',
    question: 'Quem fez mais atividades?',
    hint: 'Ranking de atividades por responsável',
    emoji: '✅',
    group: 'Atividades',
    title: 'Atividades por pessoa',
    chartType: 'ranking',
    dataSource: 'tasks',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'assigned_to',
    formatType: 'decimal',
  },
  {
    id: 'atividades_por_tipo',
    question: 'Que tipos de atividade fazemos mais?',
    hint: 'Ligação, reunião, WhatsApp e afins',
    emoji: '🗂️',
    group: 'Atividades',
    title: 'Atividades por tipo',
    chartType: 'pie',
    dataSource: 'tasks',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'activity_type',
    formatType: 'decimal',
  },
  {
    id: 'atividades_por_dia',
    question: 'Quantas atividades por dia?',
    hint: 'Volume diário de atividades concluídas',
    emoji: '📅',
    group: 'Atividades',
    title: 'Atividades por dia',
    chartType: 'bar',
    dataSource: 'tasks',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'completed_at',
    dateGrouping: 'day',
    formatType: 'decimal',
  },
  {
    id: 'leads_por_origem',
    question: 'De onde vêm os leads?',
    hint: 'Contagem de leads por origem',
    emoji: '🧲',
    group: 'Leads',
    title: 'Leads por origem',
    chartType: 'bar_horizontal',
    dataSource: 'leads',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'source',
    formatType: 'decimal',
  },
  {
    id: 'leads_por_dia',
    question: 'Quantos leads entram por dia?',
    hint: 'Evolução da entrada de leads',
    emoji: '📊',
    group: 'Leads',
    title: 'Leads por dia',
    chartType: 'line',
    dataSource: 'leads',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'created_at',
    dateGrouping: 'day',
    formatType: 'decimal',
  },
  {
    id: 'leads_total',
    question: 'Quantos leads no total?',
    hint: 'Um número grande com o total de leads',
    emoji: '🔢',
    group: 'Leads',
    title: 'Total de leads',
    chartType: 'scorecard',
    dataSource: 'leads',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'created_at',
    dateGrouping: 'month',
    formatType: 'decimal',
  },
  {
    id: 'conversas_por_setor',
    question: 'Quantas conversas por setor no RoyZapp?',
    hint: 'Volume de conversas do WhatsApp por setor',
    emoji: '💬',
    group: 'WhatsApp',
    title: 'Conversas por setor',
    chartType: 'bar_horizontal',
    dataSource: 'royzapp',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'sector_id',
    formatType: 'decimal',
  },
  {
    id: 'meta_faturamento',
    question: 'Estamos batendo a meta de faturamento?',
    hint: 'Meta x realizado dos negócios ganhos, com linha anual acumulada',
    emoji: '🎯',
    group: 'Metas',
    title: 'Meta de faturamento',
    chartType: 'goal_tracker',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'won_at',
    dateGrouping: 'month',
    formatType: 'currency',
    statusFilter: 'won',
  },
  {
    id: 'meta_negocios_fechados',
    question: 'Estamos batendo a meta de negócios fechados?',
    hint: 'Quantidade de vendas ganhas x meta do período',
    emoji: '🏁',
    group: 'Metas',
    title: 'Meta de negócios fechados',
    chartType: 'goal_tracker',
    dataSource: 'deals',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'won_at',
    dateGrouping: 'month',
    formatType: 'decimal',
    statusFilter: 'won',
  },
  {
    id: 'meta_previsao_receita',
    question: 'A previsão de receita alcança a meta?',
    hint: 'Pipeline ponderado por probabilidade x meta',
    emoji: '🔮',
    group: 'Metas',
    title: 'Meta de previsão de receita',
    chartType: 'goal_tracker',
    dataSource: 'deals',
    measureField: 'value',
    aggregation: 'sum',
    dimensionField: 'expected_close_date',
    dateGrouping: 'month',
    formatType: 'currency',
    statusFilter: 'open',
  },
  {
    id: 'meta_atividades',
    question: 'O time está batendo a meta de atividades?',
    hint: 'Atividades concluídas x meta do período',
    emoji: '✅',
    group: 'Metas',
    title: 'Meta de atividades',
    chartType: 'goal_tracker',
    dataSource: 'tasks',
    measureField: null,
    aggregation: 'count',
    dimensionField: 'completed_at',
    dateGrouping: 'month',
    formatType: 'decimal',
  },
];

export const RECIPE_GROUPS = ['Vendas', 'Metas', 'Time', 'Atividades', 'Leads', 'WhatsApp'] as const;

