// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __reExport = (target, mod, secondTarget) => (__copyProps(target, mod, "default"), secondTarget && __copyProps(secondTarget, mod, "default"));

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/telephony-calls.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/helpers.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";

// node_modules/@supabase/supabase-js/dist/module/index.js
var module_exports = {};
__export(module_exports, {
  FunctionRegion: () => FunctionRegion,
  FunctionsError: () => FunctionsError,
  FunctionsFetchError: () => FunctionsFetchError,
  FunctionsHttpError: () => FunctionsHttpError,
  FunctionsRelayError: () => FunctionsRelayError,
  PostgrestError: () => PostgrestError,
  SupabaseClient: () => SupabaseClient,
  createClient: () => createClient
});

// node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
import { FunctionsClient } from "npm:@supabase/functions-js";
import { PostgrestClient } from "npm:@supabase/postgrest-js";
import { RealtimeClient } from "npm:@supabase/realtime-js";
import { StorageClient as SupabaseStorageClient } from "npm:@supabase/storage-js";

// node_modules/@supabase/supabase-js/dist/module/lib/version.js
var version = "2.87.3";

// node_modules/@supabase/supabase-js/dist/module/lib/constants.js
var JS_ENV = "";
if (typeof Deno !== "undefined") {
  JS_ENV = "deno";
} else if (typeof document !== "undefined") {
  JS_ENV = "web";
} else if (typeof navigator !== "undefined" && navigator.product === "ReactNative") {
  JS_ENV = "react-native";
} else {
  JS_ENV = "node";
}
var DEFAULT_HEADERS = { "X-Client-Info": `supabase-js-${JS_ENV}/${version}` };
var DEFAULT_GLOBAL_OPTIONS = {
  headers: DEFAULT_HEADERS
};
var DEFAULT_DB_OPTIONS = {
  schema: "public"
};
var DEFAULT_AUTH_OPTIONS = {
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: true,
  flowType: "implicit"
};
var DEFAULT_REALTIME_OPTIONS = {};

// node_modules/@supabase/supabase-js/dist/module/lib/fetch.js
var resolveFetch = (customFetch) => {
  if (customFetch) {
    return (...args) => customFetch(...args);
  }
  return (...args) => fetch(...args);
};
var resolveHeadersConstructor = () => {
  return Headers;
};
var fetchWithAuth = (supabaseKey, getAccessToken, customFetch) => {
  const fetch2 = resolveFetch(customFetch);
  const HeadersConstructor = resolveHeadersConstructor();
  return async (input, init) => {
    var _a;
    const accessToken = (_a = await getAccessToken()) !== null && _a !== void 0 ? _a : supabaseKey;
    let headers = new HeadersConstructor(init === null || init === void 0 ? void 0 : init.headers);
    if (!headers.has("apikey")) {
      headers.set("apikey", supabaseKey);
    }
    if (!headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${accessToken}`);
    }
    return fetch2(input, Object.assign(Object.assign({}, init), { headers }));
  };
};

// node_modules/@supabase/supabase-js/dist/module/lib/helpers.js
function ensureTrailingSlash(url) {
  return url.endsWith("/") ? url : url + "/";
}
function applySettingDefaults(options, defaults) {
  var _a, _b;
  const { db: dbOptions, auth: authOptions, realtime: realtimeOptions, global: globalOptions } = options;
  const { db: DEFAULT_DB_OPTIONS2, auth: DEFAULT_AUTH_OPTIONS2, realtime: DEFAULT_REALTIME_OPTIONS2, global: DEFAULT_GLOBAL_OPTIONS2 } = defaults;
  const result = {
    db: Object.assign(Object.assign({}, DEFAULT_DB_OPTIONS2), dbOptions),
    auth: Object.assign(Object.assign({}, DEFAULT_AUTH_OPTIONS2), authOptions),
    realtime: Object.assign(Object.assign({}, DEFAULT_REALTIME_OPTIONS2), realtimeOptions),
    storage: {},
    global: Object.assign(Object.assign(Object.assign({}, DEFAULT_GLOBAL_OPTIONS2), globalOptions), { headers: Object.assign(Object.assign({}, (_a = DEFAULT_GLOBAL_OPTIONS2 === null || DEFAULT_GLOBAL_OPTIONS2 === void 0 ? void 0 : DEFAULT_GLOBAL_OPTIONS2.headers) !== null && _a !== void 0 ? _a : {}), (_b = globalOptions === null || globalOptions === void 0 ? void 0 : globalOptions.headers) !== null && _b !== void 0 ? _b : {}) }),
    accessToken: async () => ""
  };
  if (options.accessToken) {
    result.accessToken = options.accessToken;
  } else {
    delete result.accessToken;
  }
  return result;
}
function validateSupabaseUrl(supabaseUrl) {
  const trimmedUrl = supabaseUrl === null || supabaseUrl === void 0 ? void 0 : supabaseUrl.trim();
  if (!trimmedUrl) {
    throw new Error("supabaseUrl is required.");
  }
  if (!trimmedUrl.match(/^https?:\/\//i)) {
    throw new Error("Invalid supabaseUrl: Must be a valid HTTP or HTTPS URL.");
  }
  try {
    return new URL(ensureTrailingSlash(trimmedUrl));
  } catch (_a) {
    throw Error("Invalid supabaseUrl: Provided URL is malformed.");
  }
}

// node_modules/@supabase/supabase-js/dist/module/lib/SupabaseAuthClient.js
import { AuthClient } from "npm:@supabase/auth-js";
var SupabaseAuthClient = class extends AuthClient {
  constructor(options) {
    super(options);
  }
};

// node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
var SupabaseClient = class {
  /**
   * Create a new client for use in the browser.
   * @param supabaseUrl The unique Supabase URL which is supplied when you create a new project in your project dashboard.
   * @param supabaseKey The unique Supabase Key which is supplied when you create a new project in your project dashboard.
   * @param options.db.schema You can switch in between schemas. The schema needs to be on the list of exposed schemas inside Supabase.
   * @param options.auth.autoRefreshToken Set to "true" if you want to automatically refresh the token before expiring.
   * @param options.auth.persistSession Set to "true" if you want to automatically save the user session into local storage.
   * @param options.auth.detectSessionInUrl Set to "true" if you want to automatically detects OAuth grants in the URL and signs in the user.
   * @param options.realtime Options passed along to realtime-js constructor.
   * @param options.storage Options passed along to the storage-js constructor.
   * @param options.global.fetch A custom fetch implementation.
   * @param options.global.headers Any additional headers to send with each network request.
   * @example
   * ```ts
   * import { createClient } from '@supabase/supabase-js'
   *
   * const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key')
   * const { data } = await supabase.from('profiles').select('*')
   * ```
   */
  constructor(supabaseUrl, supabaseKey, options) {
    var _a, _b, _c;
    this.supabaseUrl = supabaseUrl;
    this.supabaseKey = supabaseKey;
    const baseUrl = validateSupabaseUrl(supabaseUrl);
    if (!supabaseKey)
      throw new Error("supabaseKey is required.");
    this.realtimeUrl = new URL("realtime/v1", baseUrl);
    this.realtimeUrl.protocol = this.realtimeUrl.protocol.replace("http", "ws");
    this.authUrl = new URL("auth/v1", baseUrl);
    this.storageUrl = new URL("storage/v1", baseUrl);
    this.functionsUrl = new URL("functions/v1", baseUrl);
    const defaultStorageKey = `sb-${baseUrl.hostname.split(".")[0]}-auth-token`;
    const DEFAULTS = {
      db: DEFAULT_DB_OPTIONS,
      realtime: DEFAULT_REALTIME_OPTIONS,
      auth: Object.assign(Object.assign({}, DEFAULT_AUTH_OPTIONS), { storageKey: defaultStorageKey }),
      global: DEFAULT_GLOBAL_OPTIONS
    };
    const settings = applySettingDefaults(options !== null && options !== void 0 ? options : {}, DEFAULTS);
    this.storageKey = (_a = settings.auth.storageKey) !== null && _a !== void 0 ? _a : "";
    this.headers = (_b = settings.global.headers) !== null && _b !== void 0 ? _b : {};
    if (!settings.accessToken) {
      this.auth = this._initSupabaseAuthClient((_c = settings.auth) !== null && _c !== void 0 ? _c : {}, this.headers, settings.global.fetch);
    } else {
      this.accessToken = settings.accessToken;
      this.auth = new Proxy({}, {
        get: (_, prop) => {
          throw new Error(`@supabase/supabase-js: Supabase Client is configured with the accessToken option, accessing supabase.auth.${String(prop)} is not possible`);
        }
      });
    }
    this.fetch = fetchWithAuth(supabaseKey, this._getAccessToken.bind(this), settings.global.fetch);
    this.realtime = this._initRealtimeClient(Object.assign({ headers: this.headers, accessToken: this._getAccessToken.bind(this) }, settings.realtime));
    if (this.accessToken) {
      this.accessToken().then((token) => this.realtime.setAuth(token)).catch((e) => console.warn("Failed to set initial Realtime auth token:", e));
    }
    this.rest = new PostgrestClient(new URL("rest/v1", baseUrl).href, {
      headers: this.headers,
      schema: settings.db.schema,
      fetch: this.fetch
    });
    this.storage = new SupabaseStorageClient(this.storageUrl.href, this.headers, this.fetch, options === null || options === void 0 ? void 0 : options.storage);
    if (!settings.accessToken) {
      this._listenForAuthEvents();
    }
  }
  /**
   * Supabase Functions allows you to deploy and invoke edge functions.
   */
  get functions() {
    return new FunctionsClient(this.functionsUrl.href, {
      headers: this.headers,
      customFetch: this.fetch
    });
  }
  /**
   * Perform a query on a table or a view.
   *
   * @param relation - The table or view name to query
   */
  from(relation) {
    return this.rest.from(relation);
  }
  // NOTE: signatures must be kept in sync with PostgrestClient.schema
  /**
   * Select a schema to query or perform an function (rpc) call.
   *
   * The schema needs to be on the list of exposed schemas inside Supabase.
   *
   * @param schema - The schema to query
   */
  schema(schema) {
    return this.rest.schema(schema);
  }
  // NOTE: signatures must be kept in sync with PostgrestClient.rpc
  /**
   * Perform a function call.
   *
   * @param fn - The function name to call
   * @param args - The arguments to pass to the function call
   * @param options - Named parameters
   * @param options.head - When set to `true`, `data` will not be returned.
   * Useful if you only need the count.
   * @param options.get - When set to `true`, the function will be called with
   * read-only access mode.
   * @param options.count - Count algorithm to use to count rows returned by the
   * function. Only applicable for [set-returning
   * functions](https://www.postgresql.org/docs/current/functions-srf.html).
   *
   * `"exact"`: Exact but slow count algorithm. Performs a `COUNT(*)` under the
   * hood.
   *
   * `"planned"`: Approximated but fast count algorithm. Uses the Postgres
   * statistics under the hood.
   *
   * `"estimated"`: Uses exact count for low numbers and planned count for high
   * numbers.
   */
  rpc(fn, args = {}, options = {
    head: false,
    get: false,
    count: void 0
  }) {
    return this.rest.rpc(fn, args, options);
  }
  /**
   * Creates a Realtime channel with Broadcast, Presence, and Postgres Changes.
   *
   * @param {string} name - The name of the Realtime channel.
   * @param {Object} opts - The options to pass to the Realtime channel.
   *
   */
  channel(name, opts = { config: {} }) {
    return this.realtime.channel(name, opts);
  }
  /**
   * Returns all Realtime channels.
   */
  getChannels() {
    return this.realtime.getChannels();
  }
  /**
   * Unsubscribes and removes Realtime channel from Realtime client.
   *
   * @param {RealtimeChannel} channel - The name of the Realtime channel.
   *
   */
  removeChannel(channel) {
    return this.realtime.removeChannel(channel);
  }
  /**
   * Unsubscribes and removes all Realtime channels from Realtime client.
   */
  removeAllChannels() {
    return this.realtime.removeAllChannels();
  }
  async _getAccessToken() {
    var _a, _b;
    if (this.accessToken) {
      return await this.accessToken();
    }
    const { data } = await this.auth.getSession();
    return (_b = (_a = data.session) === null || _a === void 0 ? void 0 : _a.access_token) !== null && _b !== void 0 ? _b : this.supabaseKey;
  }
  _initSupabaseAuthClient({ autoRefreshToken, persistSession, detectSessionInUrl, storage, userStorage, storageKey, flowType, lock, debug, throwOnError }, headers, fetch2) {
    const authHeaders = {
      Authorization: `Bearer ${this.supabaseKey}`,
      apikey: `${this.supabaseKey}`
    };
    return new SupabaseAuthClient({
      url: this.authUrl.href,
      headers: Object.assign(Object.assign({}, authHeaders), headers),
      storageKey,
      autoRefreshToken,
      persistSession,
      detectSessionInUrl,
      storage,
      userStorage,
      flowType,
      lock,
      debug,
      throwOnError,
      fetch: fetch2,
      // auth checks if there is a custom authorizaiton header using this flag
      // so it knows whether to return an error when getUser is called with no session
      hasCustomAuthorizationHeader: Object.keys(this.headers).some((key) => key.toLowerCase() === "authorization")
    });
  }
  _initRealtimeClient(options) {
    return new RealtimeClient(this.realtimeUrl.href, Object.assign(Object.assign({}, options), { params: Object.assign({ apikey: this.supabaseKey }, options === null || options === void 0 ? void 0 : options.params) }));
  }
  _listenForAuthEvents() {
    const data = this.auth.onAuthStateChange((event, session) => {
      this._handleTokenChanged(event, "CLIENT", session === null || session === void 0 ? void 0 : session.access_token);
    });
    return data;
  }
  _handleTokenChanged(event, source, token) {
    if ((event === "TOKEN_REFRESHED" || event === "SIGNED_IN") && this.changedAccessToken !== token) {
      this.changedAccessToken = token;
      this.realtime.setAuth(token);
    } else if (event === "SIGNED_OUT") {
      this.realtime.setAuth();
      if (source == "STORAGE")
        this.auth.signOut();
      this.changedAccessToken = void 0;
    }
  }
};

// node_modules/@supabase/supabase-js/dist/module/index.js
__reExport(module_exports, auth_js_star);
__reExport(module_exports, realtime_js_star);
import * as auth_js_star from "npm:@supabase/auth-js";
import { PostgrestError } from "npm:@supabase/postgrest-js";
import { FunctionsHttpError, FunctionsFetchError, FunctionsRelayError, FunctionsError, FunctionRegion } from "npm:@supabase/functions-js";
import * as realtime_js_star from "npm:@supabase/realtime-js";
var createClient = (supabaseUrl, supabaseKey, options) => {
  return new SupabaseClient(supabaseUrl, supabaseKey, options);
};
function shouldShowDeprecationWarning() {
  if (typeof window !== "undefined") {
    return false;
  }
  if (typeof process === "undefined") {
    return false;
  }
  const processVersion = process["version"];
  if (processVersion === void 0 || processVersion === null) {
    return false;
  }
  const versionMatch = processVersion.match(/^v(\d+)\./);
  if (!versionMatch) {
    return false;
  }
  const majorVersion = parseInt(versionMatch[1], 10);
  return majorVersion <= 18;
}
if (shouldShowDeprecationWarning()) {
  console.warn(`\u26A0\uFE0F  Node.js 18 and below are deprecated and will no longer be supported in future versions of @supabase/supabase-js. Please upgrade to Node.js 20 or later. For more information, visit: https://github.com/orgs/supabase/discussions/37217`);
}

// src/lib/mcp/supabase.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireUser(ctx) {
  if (!ctx.isAuthenticated?.() || !ctx.getUserId?.()) {
    throw new ToolError("N\xE3o autenticado. Reconecte o conector para renovar o acesso.");
  }
  return supabaseForUser(ctx);
}
async function requireSector(ctx, sectorId) {
  const supabase = requireUser(ctx);
  const userId = ctx.getUserId?.();
  if (!userId) throw new ToolError("N\xE3o autenticado. Reconecte o conector para renovar o acesso.");
  const { data, error } = await supabase.rpc("user_has_sector_access", {
    _auth_user_id: userId,
    _sector_id: sectorId
  });
  failIf(error);
  if (data !== true) throw new ToolError(`Sem permiss\xE3o para consultar a \xE1rea ${sectorId}.`);
  return supabase;
}
var RH_ALLOWED_EMAILS = /* @__PURE__ */ new Set([
  "m.quintana@me.com",
  "coachevertonsantos@gmail.com",
  "rh@anjosbusiness.com.br",
  "diessica@consultoria-luma.com",
  "jaqueline@consultoria-luma.com",
  "brualmeida.est@hotmail.com",
  "arthur.mudri@hotmail.com"
]);
async function requireRhAccess(ctx) {
  const email = (ctx.getUserEmail?.() ?? "").toLowerCase();
  if (!RH_ALLOWED_EMAILS.has(email)) throw new ToolError("Sem permiss\xE3o para consultar a \xE1rea de RH.");
  return requireSector(ctx, "rh");
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function failIf(error) {
  if (error) throw new ToolError(error.message);
}
function toIso(value, endOfDay = false) {
  if (!value) return void 0;
  const raw = /^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T${endOfDay ? "23:59:59.999" : "00:00:00.000"}Z` : value;
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) throw new ToolError(`Data inv\xE1lida: ${value}`);
  return d.toISOString();
}
function secondsToHuman(total) {
  const s = Math.max(0, Math.round(total));
  const h = Math.floor(s / 3600);
  const m = Math.floor(s % 3600 / 60);
  const sec = s % 60;
  return h > 0 ? `${h}h ${m}m ${sec}s` : m > 0 ? `${m}m ${sec}s` : `${sec}s`;
}

// src/lib/mcp/tools/telephony-calls.ts
var telephony_calls_default = defineTool({
  name: "telephony_calls",
  title: "Liga\xE7\xF5es 3C Plus",
  description: "Lista e resume as liga\xE7\xF5es da 3C Plus (volume, dura\xE7\xE3o, status, qualifica\xE7\xE3o) por per\xEDodo, vendedor, campanha ou telefone.",
  inputSchema: {
    start_date: z.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    agent_name: z.string().nullable().describe("Filtra por nome do vendedor/agente (busca parcial). Use null para todos."),
    campaign_name: z.string().nullable().describe("Filtra por campanha (busca parcial). Use null para todas."),
    direction: z.enum(["inbound", "outbound", "all"]).describe("Dire\xE7\xE3o das liga\xE7\xF5es."),
    limit: z.number().int().min(1).max(500).describe("Quantidade m\xE1xima de liga\xE7\xF5es detalhadas retornadas (ex.: 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, agent_name, campaign_name, direction, limit }, ctx) => {
    const supabase = await requireSector(ctx, "vendas");
    let query = supabase.from("threecplus_call_logs").select(
      "id, agent_name, agent_email, call_type, direction, phone, contact_name, campaign_name, status, qualification_name, duration_seconds, wait_seconds, acw_seconds, started_at, connected_at, ended_at"
    ).gte("started_at", toIso(start_date)).lte("started_at", toIso(end_date, true)).order("started_at", { ascending: false }).limit(limit);
    if (agent_name) query = query.ilike("agent_name", `%${agent_name}%`);
    if (campaign_name) query = query.ilike("campaign_name", `%${campaign_name}%`);
    if (direction !== "all") query = query.eq("direction", direction);
    const { data, error } = await query;
    failIf(error);
    const calls = data ?? [];
    const connected = calls.filter((c) => !!c.connected_at);
    const totalDuration = calls.reduce((acc, c) => acc + (c.duration_seconds ?? 0), 0);
    const byAgent = /* @__PURE__ */ new Map();
    for (const c of calls) {
      const key = c.agent_name ?? "Sem agente";
      const row = byAgent.get(key) ?? { ligacoes: 0, atendidas: 0, duracao_segundos: 0 };
      row.ligacoes += 1;
      if (c.connected_at) row.atendidas += 1;
      row.duracao_segundos += c.duration_seconds ?? 0;
      byAgent.set(key, row);
    }
    return jsonResult({
      periodo: { inicio: start_date, fim: end_date },
      resumo: {
        total_ligacoes: calls.length,
        atendidas: connected.length,
        taxa_atendimento_pct: calls.length ? Math.round(connected.length / calls.length * 1e3) / 10 : 0,
        tempo_total: secondsToHuman(totalDuration),
        duracao_media_segundos: connected.length ? Math.round(totalDuration / connected.length) : 0
      },
      por_vendedor: [...byAgent.entries()].map(([vendedor, v]) => ({ vendedor, ...v, tempo_total: secondsToHuman(v.duracao_segundos) })).sort((a, b) => b.ligacoes - a.ligacoes),
      ligacoes: calls,
      observacao: calls.length === limit ? `Resultado truncado em ${limit} liga\xE7\xF5es. Reduza o per\xEDodo ou filtre por vendedor para uma vis\xE3o completa.` : null
    });
  }
});

// src/lib/mcp/tools/sales-deals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var sales_deals_default = defineTool2({
  name: "sales_deals",
  title: "Neg\xF3cios do pipeline",
  description: "Lista neg\xF3cios do pipeline comercial com est\xE1gio, valor, respons\xE1vel, status (aberto/ganho/perdido) e motivo de perda, com resumo agregado.",
  inputSchema: {
    start_date: z2.string().nullable().describe("Data inicial de cria\xE7\xE3o (YYYY-MM-DD). null = sem limite."),
    end_date: z2.string().nullable().describe("Data final de cria\xE7\xE3o (YYYY-MM-DD). null = sem limite."),
    status: z2.enum(["open", "won", "lost", "all"]).describe("Status dos neg\xF3cios."),
    search: z2.string().nullable().describe("Busca parcial no t\xEDtulo ou nome do contato. null = sem busca."),
    limit: z2.number().int().min(1).max(500).describe("M\xE1ximo de neg\xF3cios retornados (ex.: 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, status, search, limit }, ctx) => {
    const supabase = await requireSector(ctx, "vendas");
    let query = supabase.from("deals").select(
      "id, title, status, value, entry_value, received_value, contact_name, contact_email, contact_phone, source, is_renewal, probability, expected_close_date, won_at, lost_at, lost_reason, loss_notes, stage_changed_at, created_at, updated_at, stage_id, pipeline_id, responsible_user_id, sdr_user_id, client_id, deal_stages(name), pipelines(name)"
    ).is("deleted_at", null).order("created_at", { ascending: false }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("created_at", startIso);
    if (endIso) query = query.lte("created_at", endIso);
    if (status !== "all") query = query.eq("status", status);
    if (search) query = query.or(`title.ilike.%${search}%,contact_name.ilike.%${search}%`);
    const { data, error } = await query;
    failIf(error);
    const deals = data ?? [];
    const sum = (rows) => rows.reduce((acc, d) => acc + Number(d.value ?? 0), 0);
    const won = deals.filter((d) => d.status === "won");
    const lost = deals.filter((d) => d.status === "lost");
    const byStage = /* @__PURE__ */ new Map();
    for (const d of deals) {
      const key = d.deal_stages?.name ?? "Sem est\xE1gio";
      const row = byStage.get(key) ?? { negocios: 0, valor: 0 };
      row.negocios += 1;
      row.valor += Number(d.value ?? 0);
      byStage.set(key, row);
    }
    return jsonResult({
      resumo: {
        total: deals.length,
        ganhos: won.length,
        perdidos: lost.length,
        abertos: deals.filter((d) => d.status !== "won" && d.status !== "lost").length,
        valor_total: sum(deals),
        valor_ganho: sum(won),
        taxa_conversao_pct: won.length + lost.length > 0 ? Math.round(won.length / (won.length + lost.length) * 1e3) / 10 : 0
      },
      por_estagio: [...byStage.entries()].map(([estagio, v]) => ({ estagio, ...v })),
      negocios: deals
    });
  }
});

// src/lib/mcp/tools/sales-goals-commissions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var sales_goals_commissions_default = defineTool3({
  name: "sales_goals_commissions",
  title: "Metas e comiss\xF5es",
  description: "Retorna metas comerciais do per\xEDodo e os lan\xE7amentos de comiss\xE3o por neg\xF3cio (valor, percentual, status de aprova\xE7\xE3o e pagamento).",
  inputSchema: {
    start_date: z3.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z3.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    include_goals: z3.boolean().describe("Incluir metas de vendas do per\xEDodo."),
    include_commissions: z3.boolean().describe("Incluir lan\xE7amentos de comiss\xE3o do per\xEDodo."),
    limit: z3.number().int().min(1).max(500).describe("M\xE1ximo de registros por bloco (ex.: 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, include_goals, include_commissions, limit }, ctx) => {
    const supabase = await requireSector(ctx, "vendas");
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    const payload = { periodo: { inicio: start_date, fim: end_date } };
    if (include_goals) {
      const { data, error } = await supabase.from("sales_goals").select("id, client_id, goal_amount, currency, period_start, period_end, created_at").gte("period_end", start_date).lte("period_start", end_date).order("period_start", { ascending: false }).limit(limit);
      failIf(error);
      const metas = data ?? [];
      payload.metas = metas;
      payload.metas_total = metas.reduce((acc, g) => acc + Number(g.goal_amount ?? 0), 0);
    }
    if (include_commissions) {
      const { data, error } = await supabase.from("commission_deal_entries").select(
        "id, deal_id, deal_title, client_name, deal_value, commission_percent, commission_total, commission_released, commission_pending, commission_status, payment_status, payment_method, approval_status, paid_at, released_at, period_id, plan_id, created_at"
      ).gte("created_at", startIso).lte("created_at", endIso).order("created_at", { ascending: false }).limit(limit);
      failIf(error);
      const entradas = data ?? [];
      payload.comissoes = entradas;
      payload.comissoes_resumo = {
        lancamentos: entradas.length,
        total: entradas.reduce((a, e) => a + Number(e.commission_total ?? 0), 0),
        liberado: entradas.reduce((a, e) => a + Number(e.commission_released ?? 0), 0),
        pendente: entradas.reduce((a, e) => a + Number(e.commission_pending ?? 0), 0),
        valor_negocios: entradas.reduce((a, e) => a + Number(e.deal_value ?? 0), 0)
      };
    }
    return jsonResult(payload);
  }
});

// src/lib/mcp/tools/zapp-conversations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var zapp_conversations_default = defineTool4({
  name: "zapp_conversations",
  title: "Conversas do RoyZapp",
  description: "Lista conversas do RoyZapp (WhatsApp) com contato, setor, \xFAltima mensagem e volume, filtrando por per\xEDodo ou busca.",
  inputSchema: {
    start_date: z4.string().nullable().describe("Data inicial da \xFAltima mensagem (YYYY-MM-DD). null = sem limite."),
    end_date: z4.string().nullable().describe("Data final da \xFAltima mensagem (YYYY-MM-DD). null = sem limite."),
    search: z4.string().nullable().describe("Busca parcial por nome do contato ou telefone. null = sem busca."),
    include_groups: z4.boolean().describe("Incluir grupos al\xE9m de conversas individuais."),
    limit: z4.number().int().min(1).max(200).describe("M\xE1ximo de conversas retornadas (ex.: 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, search, include_groups, limit }, ctx) => {
    const supabase = await requireSector(ctx, "royzapp");
    let query = supabase.from("zapp_conversations").select(
      "id, contact_name, phone_e164, channel, sector_id, client_id, deal_id, lead_id, is_group, unread_count, last_message_at, last_message_preview, created_at"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("last_message_at", startIso);
    if (endIso) query = query.lte("last_message_at", endIso);
    if (!include_groups) query = query.eq("is_group", false);
    if (search) query = query.or(`contact_name.ilike.%${search}%,phone_e164.ilike.%${search}%`);
    const { data, error } = await query;
    failIf(error);
    return jsonResult({ total: data?.length ?? 0, conversas: data ?? [] });
  }
});

// src/lib/mcp/tools/zapp-messages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var zapp_messages_default = defineTool5({
  name: "zapp_messages",
  title: "Mensagens de uma conversa",
  description: "Retorna as mensagens de uma conversa do RoyZapp (texto e transcri\xE7\xE3o de \xE1udio) em ordem cronol\xF3gica, para an\xE1lise de atendimento.",
  inputSchema: {
    conversation_id: z5.string().uuid().describe("ID da conversa (obtido em zapp_conversations)."),
    start_date: z5.string().nullable().describe("Data inicial (YYYY-MM-DD). null = sem limite."),
    end_date: z5.string().nullable().describe("Data final (YYYY-MM-DD). null = sem limite."),
    limit: z5.number().int().min(1).max(500).describe("M\xE1ximo de mensagens retornadas (ex.: 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, start_date, end_date, limit }, ctx) => {
    const supabase = await requireSector(ctx, "royzapp");
    let query = supabase.from("zapp_messages").select(
      "id, direction, content, transcription, message_type, media_type, sender_name, sender_phone, sender_user_id, delivery_status, sent_at"
    ).eq("zapp_conversation_id", conversation_id).is("deleted_at", null).order("sent_at", { ascending: true }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("sent_at", startIso);
    if (endIso) query = query.lte("sent_at", endIso);
    const { data, error } = await query;
    failIf(error);
    const msgs = data ?? [];
    return jsonResult({
      conversation_id,
      total: msgs.length,
      recebidas: msgs.filter((m) => m.direction === "inbound").length,
      enviadas: msgs.filter((m) => m.direction === "outbound").length,
      mensagens: msgs
    });
  }
});

// src/lib/mcp/tools/clients-portfolio.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z6 } from "npm:zod@^3.25.76";
var clients_portfolio_default = defineTool6({
  name: "clients_portfolio",
  title: "Carteira de clientes e contratos",
  description: "Analisa clientes, contratos, produtos, vencimentos e renova\xE7\xF5es da carteira de CS permitida ao usu\xE1rio. Suporta pagina\xE7\xE3o (offset) e modo resumo para analisar a base inteira.",
  inputSchema: {
    status: z6.enum(["active", "paused", "churn_risk", "churned", "no_contract", "all"]).describe("Status do cliente."),
    search: z6.string().nullable().describe("Busca pelo nome do cliente ou empresa; null para todos."),
    expiring_before: z6.string().nullable().describe("Listar contratos vencendo at\xE9 YYYY-MM-DD; null para n\xE3o filtrar."),
    limit: z6.number().int().min(1).max(1e3).describe("M\xE1ximo de clientes por p\xE1gina (at\xE9 1000)."),
    offset: z6.number().int().min(0).describe("Quantos clientes pular (pagina\xE7\xE3o). Comece em 0 e some o limit a cada p\xE1gina."),
    summary_only: z6.boolean().describe("true = devolve s\xF3 os totais da base inteira (sem listar clientes), ideal para vis\xE3o macro antes de paginar."),
    include_contracts: z6.boolean().describe("true = inclui os contratos de cada cliente da p\xE1gina.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, expiring_before, limit, offset, summary_only, include_contracts }, ctx) => {
    const supabase = await requireSector(ctx, "operacoes");
    const applyClientFilters = (query) => {
      let q = query;
      if (status !== "all") q = q.eq("status", status);
      if (search) q = q.or(`full_name.ilike.%${search}%,company_name.ilike.%${search}%`);
      return q;
    };
    const countResult = await applyClientFilters(
      supabase.from("clients").select("id", { count: "exact", head: true })
    );
    failIf(countResult.error);
    const totalClientes = countResult.count ?? 0;
    const statusCounts = {};
    if (summary_only || offset === 0) {
      const statuses = ["active", "paused", "churn_risk", "churned", "no_contract"];
      const results = await Promise.all(
        statuses.map(async (s) => {
          let q = supabase.from("clients").select("id", { count: "exact", head: true }).eq("status", s);
          if (search) q = q.or(`full_name.ilike.%${search}%,company_name.ilike.%${search}%`);
          const r = await q;
          return [s, r.error ? 0 : r.count ?? 0];
        })
      );
      results.forEach(([s, c]) => {
        statusCounts[s] = c;
      });
    }
    if (summary_only) {
      const contractsCount = await supabase.from("client_contracts").select("id", { count: "exact", head: true }).eq("status", "active");
      failIf(contractsCount.error);
      return jsonResult({
        resumo: {
          clientes_total: totalClientes,
          clientes_por_status: statusCounts,
          contratos_ativos: contractsCount.count ?? 0
        },
        paginacao: {
          modo: "summary_only",
          proximo_passo: `Chame novamente com summary_only=false, limit=1000 e offset=0, depois offset=1000, 2000... at\xE9 cobrir ${totalClientes} clientes.`
        }
      });
    }
    const clientsResult = await applyClientFilters(
      supabase.from("clients").select(
        "id, full_name, company_name, status, responsible_user_id, stage_id, business_segment, mls_level, contract_start_date, contract_end_date, recent_activity_at, created_at"
      ).order("full_name").range(offset, offset + limit - 1)
    );
    failIf(clientsResult.error);
    const clients = clientsResult.data ?? [];
    const ids = clients.map((client) => client.id);
    let contracts = [];
    if (include_contracts && ids.length) {
      let contractQuery = supabase.from("client_contracts").select(
        "id, client_id, product_id, status, value, currency, start_date, end_date, contract_type, payment_status, installments_count"
      ).in("client_id", ids).order("end_date", { ascending: true });
      if (expiring_before) contractQuery = contractQuery.lte("end_date", expiring_before);
      const result = await contractQuery.limit(3e3);
      failIf(result.error);
      contracts = result.data ?? [];
    }
    const productIds = [...new Set(contracts.map((c) => c.product_id).filter(Boolean))];
    let products = [];
    if (productIds.length) {
      const result = await supabase.from("products").select("id, name, billing_period, is_active, color").in("id", productIds);
      failIf(result.error);
      products = result.data ?? [];
    }
    const productMap = new Map(products.map((p) => [p.id, p]));
    const rows = clients.map((client) => ({
      ...client,
      contratos: include_contracts ? contracts.filter((c) => c.client_id === client.id).map((c) => ({ ...c, produto: productMap.get(c.product_id) ?? null })) : void 0
    }));
    const nextOffset = offset + clients.length;
    const hasMore = nextOffset < totalClientes;
    return jsonResult({
      resumo: {
        clientes_total: totalClientes,
        clientes_nesta_pagina: rows.length,
        clientes_por_status: offset === 0 ? statusCounts : void 0,
        contratos_nesta_pagina: contracts.length,
        contratos_ativos_nesta_pagina: contracts.filter((c) => c.status === "active").length,
        valor_contratos_nesta_pagina: contracts.reduce((sum, c) => sum + Number(c.value ?? 0), 0)
      },
      paginacao: {
        offset,
        limit,
        proximo_offset: hasMore ? nextOffset : null,
        tem_mais: hasMore,
        instrucao: hasMore ? `Ainda faltam ${totalClientes - nextOffset} clientes. Chame de novo com offset=${nextOffset} e o mesmo limit.` : "Base completa percorrida."
      },
      clientes: rows
    });
  }
});

// src/lib/mcp/tools/client-success-activity.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z7 } from "npm:zod@^3.25.76";
var client_success_activity_default = defineTool7({
  name: "client_success_activity",
  title: "Atividades de Customer Success",
  description: "Resume check-ins e acompanhamentos de clientes por per\xEDodo, canal e tipo, dentro do acesso de Opera\xE7\xF5es.",
  inputSchema: {
    start_date: z7.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z7.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    client_id: z7.string().uuid().nullable().describe("Cliente espec\xEDfico; null para toda a carteira permitida."),
    limit: z7.number().int().min(1).max(300).describe("M\xE1ximo de registros de cada tipo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, client_id, limit }, ctx) => {
    const supabase = await requireSector(ctx, "operacoes");
    const start = toIso(start_date) ?? start_date;
    const end = toIso(end_date, true) ?? end_date;
    let checkinsQuery = supabase.from("client_checkins").select("id, client_id, user_id, happened_at, initiated_by, channel, kind, summary, source, message_count").gte("happened_at", start).lte("happened_at", end).order("happened_at", { ascending: false }).limit(limit);
    let followupsQuery = supabase.from("client_followups").select("id, client_id, user_id, type, title, content, created_at").gte("created_at", start).lte("created_at", end).order("created_at", { ascending: false }).limit(limit);
    if (client_id) {
      checkinsQuery = checkinsQuery.eq("client_id", client_id);
      followupsQuery = followupsQuery.eq("client_id", client_id);
    }
    const [checkinsResult, followupsResult] = await Promise.all([checkinsQuery, followupsQuery]);
    failIf(checkinsResult.error);
    failIf(followupsResult.error);
    const checkins = checkinsResult.data ?? [];
    const followups = followupsResult.data ?? [];
    const porCanal = /* @__PURE__ */ new Map();
    checkins.forEach((row) => porCanal.set(row.channel ?? "n\xE3o informado", (porCanal.get(row.channel ?? "n\xE3o informado") ?? 0) + 1));
    return jsonResult({
      periodo: { inicio: start_date, fim: end_date },
      resumo: { checkins: checkins.length, acompanhamentos: followups.length, por_canal: Object.fromEntries(porCanal) },
      checkins,
      acompanhamentos: followups,
      observacao: checkins.length === limit || followups.length === limit ? "Resultado limitado; reduza o per\xEDodo ou informe um cliente." : null
    });
  }
});

// src/lib/mcp/tools/financial-overview.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z8 } from "npm:zod@^3.25.76";
var financial_overview_default = defineTool8({
  name: "financial_overview",
  title: "Vis\xE3o financeira",
  description: "Analisa fluxo de caixa, contas a pagar e receber e inadimpl\xEAncia sem expor anexos, dados banc\xE1rios ou credenciais.",
  inputSchema: {
    start_date: z8.string().describe("In\xEDcio do per\xEDodo por vencimento (YYYY-MM-DD)."),
    end_date: z8.string().describe("Fim do per\xEDodo por vencimento (YYYY-MM-DD)."),
    entry_type: z8.enum(["receivable", "payable", "all"]).describe("Tipo de lan\xE7amento."),
    status: z8.enum(["pending", "paid", "overdue", "partially_paid", "cancelled", "all"]).describe("Status financeiro."),
    include_entries: z8.boolean().describe("Incluir lista resumida dos lan\xE7amentos."),
    limit: z8.number().int().min(1).max(300).describe("M\xE1ximo de lan\xE7amentos detalhados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, entry_type, status, include_entries, limit }, ctx) => {
    const supabase = await requireSector(ctx, "financeiro");
    let query = supabase.from("financial_entries").select("id, entry_type, description, amount, currency, due_date, payment_date, status, category_id, client_id, supplier_id, installment_number, total_installments, is_conciliated").gte("due_date", start_date).lte("due_date", end_date).order("due_date").limit(limit);
    if (entry_type !== "all") query = query.eq("entry_type", entry_type);
    if (status !== "all") query = query.eq("status", status);
    const { data, error } = await query;
    failIf(error);
    const entries = data ?? [];
    const total = (rows) => rows.reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
    const receivables = entries.filter((row) => row.entry_type === "receivable");
    const payables = entries.filter((row) => row.entry_type === "payable");
    const byStatus = /* @__PURE__ */ new Map();
    entries.forEach((row) => {
      const key = row.status ?? "n\xE3o informado";
      const current = byStatus.get(key) ?? { quantidade: 0, valor: 0 };
      current.quantidade += 1;
      current.valor += Number(row.amount ?? 0);
      byStatus.set(key, current);
    });
    return jsonResult({
      periodo: { inicio: start_date, fim: end_date },
      resumo: { lancamentos: entries.length, a_receber: total(receivables), a_pagar: total(payables), saldo_previsto: total(receivables) - total(payables), conciliados: entries.filter((e) => e.is_conciliated).length },
      por_status: [...byStatus.entries()].map(([nome, values]) => ({ status: nome, ...values })),
      lancamentos: include_entries ? entries : void 0,
      observacao: entries.length === limit ? `An\xE1lise limitada aos primeiros ${limit} lan\xE7amentos do filtro.` : null
    });
  }
});

// src/lib/mcp/tools/hr-overview.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z9 } from "npm:zod@^3.25.76";
var hr_overview_default = defineTool9({
  name: "hr_overview",
  title: "Indicadores de RH",
  description: "Retorna quadro de pessoas, admiss\xF5es, desligamentos e f\xE9rias sem sal\xE1rios, documentos ou dados pessoais sens\xEDveis.",
  inputSchema: {
    status: z9.enum(["active", "inactive", "all"]).describe("Status dos colaboradores."),
    department: z9.string().nullable().describe("Departamento exato; null para todos."),
    include_people: z9.boolean().describe("Incluir lista profissional resumida de colaboradores."),
    limit: z9.number().int().min(1).max(300).describe("M\xE1ximo de registros por bloco.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, department, include_people, limit }, ctx) => {
    const supabase = await requireRhAccess(ctx);
    let peopleQuery = supabase.from("hr_collaborators").select("id, full_name, department, position, hire_date, termination_date, employment_type, status, work_model, unit").order("full_name").limit(limit);
    if (status !== "all") peopleQuery = peopleQuery.eq("status", status);
    if (department) peopleQuery = peopleQuery.eq("department", department);
    const [peopleResult, vacationsResult, admissionsResult, offboardingsResult] = await Promise.all([
      peopleQuery,
      supabase.from("hr_vacation_requests").select("id, collaborator_id, request_type, start_date, end_date, days_count, status").order("start_date", { ascending: false }).limit(limit),
      supabase.from("hr_admissions").select("id, candidate_name, position_title, department, contract_type, start_date, stage, admitted_at").order("start_date", { ascending: false }).limit(limit),
      supabase.from("hr_offboardings").select("id, collaborator_id, termination_type, last_day_worked, termination_date, notice_type, stage, will_replace, completed_at").order("termination_date", { ascending: false }).limit(limit)
    ]);
    failIf(peopleResult.error);
    failIf(vacationsResult.error);
    failIf(admissionsResult.error);
    failIf(offboardingsResult.error);
    const people = peopleResult.data ?? [];
    const departments = /* @__PURE__ */ new Map();
    people.forEach((person) => departments.set(person.department ?? "N\xE3o informado", (departments.get(person.department ?? "N\xE3o informado") ?? 0) + 1));
    return jsonResult({
      resumo: { colaboradores: people.length, ativos: people.filter((p) => p.status === "active").length, por_departamento: Object.fromEntries(departments), ferias: vacationsResult.data?.length ?? 0, admissoes: admissionsResult.data?.length ?? 0, desligamentos: offboardingsResult.data?.length ?? 0 },
      colaboradores: include_people ? people : void 0,
      ferias: vacationsResult.data ?? [],
      admissoes: admissionsResult.data ?? [],
      desligamentos: offboardingsResult.data ?? [],
      privacidade: "Sal\xE1rios, documentos, CPF, RG, endere\xE7o, dados m\xE9dicos e contatos pessoais n\xE3o s\xE3o disponibilizados."
    });
  }
});

// src/lib/mcp/tools/marketing-overview.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z10 } from "npm:zod@^3.25.76";
var marketing_overview_default = defineTool10({
  name: "marketing_overview",
  title: "Projetos e conte\xFAdo de Marketing",
  description: "Analisa projetos, tarefas e calend\xE1rio de conte\xFAdo de Marketing dentro das permiss\xF5es do usu\xE1rio.",
  inputSchema: {
    start_date: z10.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z10.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    project_status: z10.string().nullable().describe("Status de projeto; null para todos."),
    limit: z10.number().int().min(1).max(300).describe("M\xE1ximo de registros por bloco.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, project_status, limit }, ctx) => {
    const supabase = await requireSector(ctx, "marketing");
    let projectsQuery = supabase.from("marketing_projects").select("id, name, description, status, start_date, target_date, budget_planned, budget_actual, owner_user_id").lte("start_date", end_date).order("target_date").limit(limit);
    if (project_status) projectsQuery = projectsQuery.eq("status", project_status);
    const [projectsResult, tasksResult, contentResult] = await Promise.all([
      projectsQuery,
      supabase.from("marketing_tasks").select("id, title, description, priority, status, due_date, is_completed, completed_at, assignee_id").gte("due_date", start_date).lte("due_date", end_date).order("due_date").limit(limit),
      supabase.from("content_pieces").select("id, title, platform, format, scheduled_date, status, hook, cta, published_url, talent_id, pillar_id").gte("scheduled_date", start_date).lte("scheduled_date", end_date).order("scheduled_date").limit(limit)
    ]);
    failIf(projectsResult.error);
    failIf(tasksResult.error);
    failIf(contentResult.error);
    const projects = projectsResult.data ?? [];
    const tasks = tasksResult.data ?? [];
    const content = contentResult.data ?? [];
    return jsonResult({
      periodo: { inicio: start_date, fim: end_date },
      resumo: { projetos: projects.length, orcamento_planejado: projects.reduce((s, p) => s + Number(p.budget_planned ?? 0), 0), orcamento_realizado: projects.reduce((s, p) => s + Number(p.budget_actual ?? 0), 0), tarefas: tasks.length, tarefas_concluidas: tasks.filter((t) => t.is_completed).length, conteudos: content.length, conteudos_publicados: content.filter((c) => c.status === "published").length },
      projetos: projects,
      tarefas: tasks,
      conteudos: content,
      observacao: projects.length === limit || tasks.length === limit || content.length === limit ? "Resultado limitado; reduza o per\xEDodo para continuar." : null
    });
  }
});

// src/lib/mcp/tools/events-overview.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z11 } from "npm:zod@^3.25.76";
var events_overview_default = defineTool11({
  name: "events_overview",
  title: "Vis\xE3o de eventos",
  description: "Analisa agenda, confirma\xE7\xF5es, presen\xE7a, capacidade, or\xE7amento e custos dos eventos permitidos ao usu\xE1rio.",
  inputSchema: {
    start_date: z11.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z11.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    status: z11.string().nullable().describe("Status do evento; null para todos."),
    limit: z11.number().int().min(1).max(200).describe("M\xE1ximo de eventos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, status, limit }, ctx) => {
    const supabase = await requireSector(ctx, "eventos");
    let query = supabase.from("events").select("id, title, description, event_type, scheduled_at, ends_at, duration_minutes, modality, address, status, budget, expected_attendees, max_capacity, category, goals").gte("scheduled_at", toIso(start_date) ?? start_date).lte("scheduled_at", toIso(end_date, true) ?? end_date).order("scheduled_at").limit(limit);
    if (status) query = query.eq("status", status);
    const eventsResult = await query;
    failIf(eventsResult.error);
    const events = eventsResult.data ?? [];
    const ids = events.map((event) => event.id);
    let participants = [];
    let costs = [];
    if (ids.length) {
      const [participantsResult, costsResult] = await Promise.all([
        supabase.from("event_participants").select("id, event_id, guest_name, rsvp_status, invited_at, rsvp_responded_at").in("event_id", ids).limit(1e3),
        supabase.from("event_costs").select("id, event_id, description, category, estimated_value, actual_value, status, supplier, due_date, paid_at").in("event_id", ids).limit(1e3)
      ]);
      failIf(participantsResult.error);
      failIf(costsResult.error);
      participants = participantsResult.data ?? [];
      costs = costsResult.data ?? [];
    }
    const rows = events.map((event) => {
      const eventParticipants = participants.filter((p) => p.event_id === event.id);
      const eventCosts = costs.filter((c) => c.event_id === event.id);
      return { ...event, participantes: { total: eventParticipants.length, confirmados: eventParticipants.filter((p) => ["confirmed", "attended"].includes(p.rsvp_status)).length, presentes: eventParticipants.filter((p) => p.rsvp_status === "attended").length, lista: eventParticipants }, custos: { estimado: eventCosts.reduce((s, c) => s + Number(c.estimated_value ?? 0), 0), realizado: eventCosts.reduce((s, c) => s + Number(c.actual_value ?? 0), 0), itens: eventCosts } };
    });
    return jsonResult({ periodo: { inicio: start_date, fim: end_date }, resumo: { eventos: rows.length, participantes: participants.length, custo_realizado: costs.reduce((s, c) => s + Number(c.actual_value ?? 0), 0) }, eventos: rows, observacao: events.length === limit ? `Resultado limitado a ${limit} eventos.` : null });
  }
});

// src/lib/mcp/tools/tasks-overview.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z12 } from "npm:zod@^3.25.76";
var tasks_overview_default = defineTool12({
  name: "tasks_overview",
  title: "Atividades e pend\xEAncias",
  description: "Lista e resume atividades internas permitidas ao usu\xE1rio, com respons\xE1veis, prazos, prioridades e v\xEDnculos.",
  inputSchema: {
    start_date: z12.string().nullable().describe("Prazo inicial (YYYY-MM-DD); null sem limite."),
    end_date: z12.string().nullable().describe("Prazo final (YYYY-MM-DD); null sem limite."),
    status: z12.enum(["pending", "in_progress", "done", "overdue", "cancelled", "all"]).describe("Status da atividade."),
    assigned_to: z12.string().uuid().nullable().describe("Respons\xE1vel espec\xEDfico; null para todos os permitidos."),
    limit: z12.number().int().min(1).max(300).describe("M\xE1ximo de atividades.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, status, assigned_to, limit }, ctx) => {
    const supabase = await requireSector(ctx, "operacoes");
    let query = supabase.from("internal_tasks").select("id, title, description, status, priority, due_date, due_time, assigned_to, client_id, deal_id, lead_id, activity_type_id, completed_at, created_at, contact_channel").order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (start_date) query = query.gte("due_date", start_date);
    if (end_date) query = query.lte("due_date", end_date);
    if (status !== "all") query = query.eq("status", status);
    if (assigned_to) query = query.eq("assigned_to", assigned_to);
    const { data, error } = await query;
    failIf(error);
    const tasks = data ?? [];
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    return jsonResult({ resumo: { atividades: tasks.length, concluidas: tasks.filter((t) => t.status === "done").length, vencidas: tasks.filter((t) => t.status !== "done" && t.status !== "cancelled" && t.due_date && t.due_date < today).length }, atividades: tasks, observacao: tasks.length === limit ? `Resultado limitado a ${limit} atividades.` : null });
  }
});

// src/lib/mcp/tools/products-overview.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z13 } from "npm:zod@^3.25.76";
var products_overview_default = defineTool13({
  name: "products_overview",
  title: "Produtos e base contratada",
  description: "Analisa o cat\xE1logo de produtos e sua presen\xE7a em clientes e contratos ativos.",
  inputSchema: {
    include_inactive: z13.boolean().describe("Incluir produtos inativos."),
    limit: z13.number().int().min(1).max(200).describe("M\xE1ximo de produtos.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive, limit }, ctx) => {
    const supabase = await requireSector(ctx, "operacoes");
    let productsQuery = supabase.from("products").select("id, name, description, price, cash_price, installment_price, billing_period, is_active, is_renewal, color").order("name").limit(limit);
    if (!include_inactive) productsQuery = productsQuery.eq("is_active", true);
    const productsResult = await productsQuery;
    failIf(productsResult.error);
    const products = productsResult.data ?? [];
    const ids = products.map((product) => product.id);
    let clientProducts = [];
    let contracts = [];
    if (ids.length) {
      const [cpResult, contractResult] = await Promise.all([
        supabase.from("client_products").select("client_id, product_id, is_active").in("product_id", ids).limit(1e3),
        supabase.from("client_contracts").select("id, client_id, product_id, status, value, start_date, end_date").in("product_id", ids).limit(1e3)
      ]);
      failIf(cpResult.error);
      failIf(contractResult.error);
      clientProducts = cpResult.data ?? [];
      contracts = contractResult.data ?? [];
    }
    return jsonResult({ produtos: products.map((product) => {
      const related = contracts.filter((c) => c.product_id === product.id);
      return { ...product, clientes_ativos: clientProducts.filter((cp) => cp.product_id === product.id && cp.is_active).length, contratos_ativos: related.filter((c) => c.status === "active").length, valor_contratado_ativo: related.filter((c) => c.status === "active").reduce((s, c) => s + Number(c.value ?? 0), 0) };
    }), observacao: products.length === limit ? `Resultado limitado a ${limit} produtos.` : null });
  }
});

// src/lib/mcp/tools/audit-overview.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z14 } from "npm:zod@^3.25.76";
var audit_overview_default = defineTool14({
  name: "audit_overview",
  title: "Auditoria gerencial",
  description: "Consulta movimenta\xE7\xF5es operacionais auditadas sem expor endere\xE7os de rede, dispositivos ou credenciais.",
  inputSchema: {
    start_date: z14.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z14.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    entity_type: z14.string().nullable().describe("Tipo de registro; null para todos."),
    action: z14.string().nullable().describe("A\xE7\xE3o auditada; null para todas."),
    limit: z14.number().int().min(1).max(300).describe("M\xE1ximo de movimenta\xE7\xF5es.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, entity_type, action, limit }, ctx) => {
    const supabase = await requireSector(ctx, "configuracoes");
    let query = supabase.from("audit_logs").select("id, user_id, user_name, action, entity_type, entity_id, entity_name, created_at").gte("created_at", toIso(start_date) ?? start_date).lte("created_at", toIso(end_date, true) ?? end_date).order("created_at", { ascending: false }).limit(limit);
    if (entity_type) query = query.eq("entity_type", entity_type);
    if (action) query = query.eq("action", action);
    const { data, error } = await query;
    failIf(error);
    const logs = data ?? [];
    const byAction = /* @__PURE__ */ new Map();
    logs.forEach((row) => byAction.set(row.action, (byAction.get(row.action) ?? 0) + 1));
    return jsonResult({ periodo: { inicio: start_date, fim: end_date }, resumo: { movimentacoes: logs.length, por_acao: Object.fromEntries(byAction) }, movimentacoes: logs, privacidade: "Detalhes livres, e-mail, endere\xE7o de rede e identifica\xE7\xE3o do dispositivo foram omitidos.", observacao: logs.length === limit ? `Resultado limitado a ${limit} movimenta\xE7\xF5es.` : null });
  }
});

// src/lib/mcp/index.ts
var projectRef = "mtzoavtbtqflufyccern";
var mcp_default = defineMcp({
  name: "roy-eternum",
  title: "ROY ETERNUM",
  version: "1.0.0",
  instructions: "Ferramentas de an\xE1lise de todas as \xE1reas do ROY ETERNUM: vendas, telefonia, RoyZapp, clientes e contratos, Customer Success, financeiro, RH, marketing, eventos, produtos, tarefas e auditoria gerencial. Todas s\xE3o estritamente somente leitura, usam a identidade do usu\xE1rio conectado e respeitam RLS, conta e acesso setorial. N\xE3o solicite dados fora da permiss\xE3o do usu\xE1rio. Datas no formato YYYY-MM-DD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    telephony_calls_default,
    sales_deals_default,
    sales_goals_commissions_default,
    zapp_conversations_default,
    zapp_messages_default,
    clients_portfolio_default,
    client_success_activity_default,
    financial_overview_default,
    hr_overview_default,
    marketing_overview_default,
    events_overview_default,
    tasks_overview_default,
    products_overview_default,
    audit_overview_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
