// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __reExport = (target, mod, secondTarget) => (__copyProps(target, mod, "default"), secondTarget && __copyProps(secondTarget, mod, "default"));

// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/telephony-calls.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/helpers.ts
import { ToolError } from "npm:@lovable.dev/mcp-js@0.28.0";

// node_modules/@supabase/supabase-js/dist/module/index.js
var module_exports = {};
__export(module_exports, {
  FunctionRegion: () => FunctionRegion,
  FunctionsError: () => FunctionsError,
  FunctionsFetchError: () => FunctionsFetchError,
  FunctionsHttpError: () => FunctionsHttpError,
  FunctionsRelayError: () => FunctionsRelayError,
  PostgrestError: () => PostgrestError,
  SupabaseClient: () => SupabaseClient,
  createClient: () => createClient
});

// node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
import { FunctionsClient } from "npm:@supabase/functions-js";
import { PostgrestClient } from "npm:@supabase/postgrest-js";
import { RealtimeClient } from "npm:@supabase/realtime-js";
import { StorageClient as SupabaseStorageClient } from "npm:@supabase/storage-js";

// node_modules/@supabase/supabase-js/dist/module/lib/version.js
var version = "2.87.3";

// node_modules/@supabase/supabase-js/dist/module/lib/constants.js
var JS_ENV = "";
if (typeof Deno !== "undefined") {
  JS_ENV = "deno";
} else if (typeof document !== "undefined") {
  JS_ENV = "web";
} else if (typeof navigator !== "undefined" && navigator.product === "ReactNative") {
  JS_ENV = "react-native";
} else {
  JS_ENV = "node";
}
var DEFAULT_HEADERS = { "X-Client-Info": `supabase-js-${JS_ENV}/${version}` };
var DEFAULT_GLOBAL_OPTIONS = {
  headers: DEFAULT_HEADERS
};
var DEFAULT_DB_OPTIONS = {
  schema: "public"
};
var DEFAULT_AUTH_OPTIONS = {
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: true,
  flowType: "implicit"
};
var DEFAULT_REALTIME_OPTIONS = {};

// node_modules/@supabase/supabase-js/dist/module/lib/fetch.js
var resolveFetch = (customFetch) => {
  if (customFetch) {
    return (...args) => customFetch(...args);
  }
  return (...args) => fetch(...args);
};
var resolveHeadersConstructor = () => {
  return Headers;
};
var fetchWithAuth = (supabaseKey, getAccessToken, customFetch) => {
  const fetch2 = resolveFetch(customFetch);
  const HeadersConstructor = resolveHeadersConstructor();
  return async (input, init) => {
    var _a;
    const accessToken = (_a = await getAccessToken()) !== null && _a !== void 0 ? _a : supabaseKey;
    let headers = new HeadersConstructor(init === null || init === void 0 ? void 0 : init.headers);
    if (!headers.has("apikey")) {
      headers.set("apikey", supabaseKey);
    }
    if (!headers.has("Authorization")) {
      headers.set("Authorization", `Bearer ${accessToken}`);
    }
    return fetch2(input, Object.assign(Object.assign({}, init), { headers }));
  };
};

// node_modules/@supabase/supabase-js/dist/module/lib/helpers.js
function ensureTrailingSlash(url) {
  return url.endsWith("/") ? url : url + "/";
}
function applySettingDefaults(options, defaults) {
  var _a, _b;
  const { db: dbOptions, auth: authOptions, realtime: realtimeOptions, global: globalOptions } = options;
  const { db: DEFAULT_DB_OPTIONS2, auth: DEFAULT_AUTH_OPTIONS2, realtime: DEFAULT_REALTIME_OPTIONS2, global: DEFAULT_GLOBAL_OPTIONS2 } = defaults;
  const result = {
    db: Object.assign(Object.assign({}, DEFAULT_DB_OPTIONS2), dbOptions),
    auth: Object.assign(Object.assign({}, DEFAULT_AUTH_OPTIONS2), authOptions),
    realtime: Object.assign(Object.assign({}, DEFAULT_REALTIME_OPTIONS2), realtimeOptions),
    storage: {},
    global: Object.assign(Object.assign(Object.assign({}, DEFAULT_GLOBAL_OPTIONS2), globalOptions), { headers: Object.assign(Object.assign({}, (_a = DEFAULT_GLOBAL_OPTIONS2 === null || DEFAULT_GLOBAL_OPTIONS2 === void 0 ? void 0 : DEFAULT_GLOBAL_OPTIONS2.headers) !== null && _a !== void 0 ? _a : {}), (_b = globalOptions === null || globalOptions === void 0 ? void 0 : globalOptions.headers) !== null && _b !== void 0 ? _b : {}) }),
    accessToken: async () => ""
  };
  if (options.accessToken) {
    result.accessToken = options.accessToken;
  } else {
    delete result.accessToken;
  }
  return result;
}
function validateSupabaseUrl(supabaseUrl) {
  const trimmedUrl = supabaseUrl === null || supabaseUrl === void 0 ? void 0 : supabaseUrl.trim();
  if (!trimmedUrl) {
    throw new Error("supabaseUrl is required.");
  }
  if (!trimmedUrl.match(/^https?:\/\//i)) {
    throw new Error("Invalid supabaseUrl: Must be a valid HTTP or HTTPS URL.");
  }
  try {
    return new URL(ensureTrailingSlash(trimmedUrl));
  } catch (_a) {
    throw Error("Invalid supabaseUrl: Provided URL is malformed.");
  }
}

// node_modules/@supabase/supabase-js/dist/module/lib/SupabaseAuthClient.js
import { AuthClient } from "npm:@supabase/auth-js";
var SupabaseAuthClient = class extends AuthClient {
  constructor(options) {
    super(options);
  }
};

// node_modules/@supabase/supabase-js/dist/module/SupabaseClient.js
var SupabaseClient = class {
  /**
   * Create a new client for use in the browser.
   * @param supabaseUrl The unique Supabase URL which is supplied when you create a new project in your project dashboard.
   * @param supabaseKey The unique Supabase Key which is supplied when you create a new project in your project dashboard.
   * @param options.db.schema You can switch in between schemas. The schema needs to be on the list of exposed schemas inside Supabase.
   * @param options.auth.autoRefreshToken Set to "true" if you want to automatically refresh the token before expiring.
   * @param options.auth.persistSession Set to "true" if you want to automatically save the user session into local storage.
   * @param options.auth.detectSessionInUrl Set to "true" if you want to automatically detects OAuth grants in the URL and signs in the user.
   * @param options.realtime Options passed along to realtime-js constructor.
   * @param options.storage Options passed along to the storage-js constructor.
   * @param options.global.fetch A custom fetch implementation.
   * @param options.global.headers Any additional headers to send with each network request.
   * @example
   * ```ts
   * import { createClient } from '@supabase/supabase-js'
   *
   * const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key')
   * const { data } = await supabase.from('profiles').select('*')
   * ```
   */
  constructor(supabaseUrl, supabaseKey, options) {
    var _a, _b, _c;
    this.supabaseUrl = supabaseUrl;
    this.supabaseKey = supabaseKey;
    const baseUrl = validateSupabaseUrl(supabaseUrl);
    if (!supabaseKey)
      throw new Error("supabaseKey is required.");
    this.realtimeUrl = new URL("realtime/v1", baseUrl);
    this.realtimeUrl.protocol = this.realtimeUrl.protocol.replace("http", "ws");
    this.authUrl = new URL("auth/v1", baseUrl);
    this.storageUrl = new URL("storage/v1", baseUrl);
    this.functionsUrl = new URL("functions/v1", baseUrl);
    const defaultStorageKey = `sb-${baseUrl.hostname.split(".")[0]}-auth-token`;
    const DEFAULTS = {
      db: DEFAULT_DB_OPTIONS,
      realtime: DEFAULT_REALTIME_OPTIONS,
      auth: Object.assign(Object.assign({}, DEFAULT_AUTH_OPTIONS), { storageKey: defaultStorageKey }),
      global: DEFAULT_GLOBAL_OPTIONS
    };
    const settings = applySettingDefaults(options !== null && options !== void 0 ? options : {}, DEFAULTS);
    this.storageKey = (_a = settings.auth.storageKey) !== null && _a !== void 0 ? _a : "";
    this.headers = (_b = settings.global.headers) !== null && _b !== void 0 ? _b : {};
    if (!settings.accessToken) {
      this.auth = this._initSupabaseAuthClient((_c = settings.auth) !== null && _c !== void 0 ? _c : {}, this.headers, settings.global.fetch);
    } else {
      this.accessToken = settings.accessToken;
      this.auth = new Proxy({}, {
        get: (_, prop) => {
          throw new Error(`@supabase/supabase-js: Supabase Client is configured with the accessToken option, accessing supabase.auth.${String(prop)} is not possible`);
        }
      });
    }
    this.fetch = fetchWithAuth(supabaseKey, this._getAccessToken.bind(this), settings.global.fetch);
    this.realtime = this._initRealtimeClient(Object.assign({ headers: this.headers, accessToken: this._getAccessToken.bind(this) }, settings.realtime));
    if (this.accessToken) {
      this.accessToken().then((token) => this.realtime.setAuth(token)).catch((e) => console.warn("Failed to set initial Realtime auth token:", e));
    }
    this.rest = new PostgrestClient(new URL("rest/v1", baseUrl).href, {
      headers: this.headers,
      schema: settings.db.schema,
      fetch: this.fetch
    });
    this.storage = new SupabaseStorageClient(this.storageUrl.href, this.headers, this.fetch, options === null || options === void 0 ? void 0 : options.storage);
    if (!settings.accessToken) {
      this._listenForAuthEvents();
    }
  }
  /**
   * Supabase Functions allows you to deploy and invoke edge functions.
   */
  get functions() {
    return new FunctionsClient(this.functionsUrl.href, {
      headers: this.headers,
      customFetch: this.fetch
    });
  }
  /**
   * Perform a query on a table or a view.
   *
   * @param relation - The table or view name to query
   */
  from(relation) {
    return this.rest.from(relation);
  }
  // NOTE: signatures must be kept in sync with PostgrestClient.schema
  /**
   * Select a schema to query or perform an function (rpc) call.
   *
   * The schema needs to be on the list of exposed schemas inside Supabase.
   *
   * @param schema - The schema to query
   */
  schema(schema) {
    return this.rest.schema(schema);
  }
  // NOTE: signatures must be kept in sync with PostgrestClient.rpc
  /**
   * Perform a function call.
   *
   * @param fn - The function name to call
   * @param args - The arguments to pass to the function call
   * @param options - Named parameters
   * @param options.head - When set to `true`, `data` will not be returned.
   * Useful if you only need the count.
   * @param options.get - When set to `true`, the function will be called with
   * read-only access mode.
   * @param options.count - Count algorithm to use to count rows returned by the
   * function. Only applicable for [set-returning
   * functions](https://www.postgresql.org/docs/current/functions-srf.html).
   *
   * `"exact"`: Exact but slow count algorithm. Performs a `COUNT(*)` under the
   * hood.
   *
   * `"planned"`: Approximated but fast count algorithm. Uses the Postgres
   * statistics under the hood.
   *
   * `"estimated"`: Uses exact count for low numbers and planned count for high
   * numbers.
   */
  rpc(fn, args = {}, options = {
    head: false,
    get: false,
    count: void 0
  }) {
    return this.rest.rpc(fn, args, options);
  }
  /**
   * Creates a Realtime channel with Broadcast, Presence, and Postgres Changes.
   *
   * @param {string} name - The name of the Realtime channel.
   * @param {Object} opts - The options to pass to the Realtime channel.
   *
   */
  channel(name, opts = { config: {} }) {
    return this.realtime.channel(name, opts);
  }
  /**
   * Returns all Realtime channels.
   */
  getChannels() {
    return this.realtime.getChannels();
  }
  /**
   * Unsubscribes and removes Realtime channel from Realtime client.
   *
   * @param {RealtimeChannel} channel - The name of the Realtime channel.
   *
   */
  removeChannel(channel) {
    return this.realtime.removeChannel(channel);
  }
  /**
   * Unsubscribes and removes all Realtime channels from Realtime client.
   */
  removeAllChannels() {
    return this.realtime.removeAllChannels();
  }
  async _getAccessToken() {
    var _a, _b;
    if (this.accessToken) {
      return await this.accessToken();
    }
    const { data } = await this.auth.getSession();
    return (_b = (_a = data.session) === null || _a === void 0 ? void 0 : _a.access_token) !== null && _b !== void 0 ? _b : this.supabaseKey;
  }
  _initSupabaseAuthClient({ autoRefreshToken, persistSession, detectSessionInUrl, storage, userStorage, storageKey, flowType, lock, debug, throwOnError }, headers, fetch2) {
    const authHeaders = {
      Authorization: `Bearer ${this.supabaseKey}`,
      apikey: `${this.supabaseKey}`
    };
    return new SupabaseAuthClient({
      url: this.authUrl.href,
      headers: Object.assign(Object.assign({}, authHeaders), headers),
      storageKey,
      autoRefreshToken,
      persistSession,
      detectSessionInUrl,
      storage,
      userStorage,
      flowType,
      lock,
      debug,
      throwOnError,
      fetch: fetch2,
      // auth checks if there is a custom authorizaiton header using this flag
      // so it knows whether to return an error when getUser is called with no session
      hasCustomAuthorizationHeader: Object.keys(this.headers).some((key) => key.toLowerCase() === "authorization")
    });
  }
  _initRealtimeClient(options) {
    return new RealtimeClient(this.realtimeUrl.href, Object.assign(Object.assign({}, options), { params: Object.assign({ apikey: this.supabaseKey }, options === null || options === void 0 ? void 0 : options.params) }));
  }
  _listenForAuthEvents() {
    const data = this.auth.onAuthStateChange((event, session) => {
      this._handleTokenChanged(event, "CLIENT", session === null || session === void 0 ? void 0 : session.access_token);
    });
    return data;
  }
  _handleTokenChanged(event, source, token) {
    if ((event === "TOKEN_REFRESHED" || event === "SIGNED_IN") && this.changedAccessToken !== token) {
      this.changedAccessToken = token;
      this.realtime.setAuth(token);
    } else if (event === "SIGNED_OUT") {
      this.realtime.setAuth();
      if (source == "STORAGE")
        this.auth.signOut();
      this.changedAccessToken = void 0;
    }
  }
};

// node_modules/@supabase/supabase-js/dist/module/index.js
__reExport(module_exports, auth_js_star);
__reExport(module_exports, realtime_js_star);
import * as auth_js_star from "npm:@supabase/auth-js";
import { PostgrestError } from "npm:@supabase/postgrest-js";
import { FunctionsHttpError, FunctionsFetchError, FunctionsRelayError, FunctionsError, FunctionRegion } from "npm:@supabase/functions-js";
import * as realtime_js_star from "npm:@supabase/realtime-js";
var createClient = (supabaseUrl, supabaseKey, options) => {
  return new SupabaseClient(supabaseUrl, supabaseKey, options);
};
function shouldShowDeprecationWarning() {
  if (typeof window !== "undefined") {
    return false;
  }
  if (typeof process === "undefined") {
    return false;
  }
  const processVersion = process["version"];
  if (processVersion === void 0 || processVersion === null) {
    return false;
  }
  const versionMatch = processVersion.match(/^v(\d+)\./);
  if (!versionMatch) {
    return false;
  }
  const majorVersion = parseInt(versionMatch[1], 10);
  return majorVersion <= 18;
}
if (shouldShowDeprecationWarning()) {
  console.warn(`\u26A0\uFE0F  Node.js 18 and below are deprecated and will no longer be supported in future versions of @supabase/supabase-js. Please upgrade to Node.js 20 or later. For more information, visit: https://github.com/orgs/supabase/discussions/37217`);
}

// src/lib/mcp/supabase.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireUser(ctx) {
  if (!ctx.isAuthenticated?.() || !ctx.getUserId?.()) {
    throw new ToolError("N\xE3o autenticado. Reconecte o conector para renovar o acesso.");
  }
  return supabaseForUser(ctx);
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function failIf(error) {
  if (error) throw new ToolError(error.message);
}
function toIso(value, endOfDay = false) {
  if (!value) return void 0;
  const raw = /^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T${endOfDay ? "23:59:59.999" : "00:00:00.000"}Z` : value;
  const d = new Date(raw);
  if (Number.isNaN(d.getTime())) throw new ToolError(`Data inv\xE1lida: ${value}`);
  return d.toISOString();
}
function secondsToHuman(total) {
  const s = Math.max(0, Math.round(total));
  const h = Math.floor(s / 3600);
  const m = Math.floor(s % 3600 / 60);
  const sec = s % 60;
  return h > 0 ? `${h}h ${m}m ${sec}s` : m > 0 ? `${m}m ${sec}s` : `${sec}s`;
}

// src/lib/mcp/tools/telephony-calls.ts
var telephony_calls_default = defineTool({
  name: "telephony_calls",
  title: "Liga\xE7\xF5es 3C Plus",
  description: "Lista e resume as liga\xE7\xF5es da 3C Plus (volume, dura\xE7\xE3o, status, qualifica\xE7\xE3o) por per\xEDodo, vendedor, campanha ou telefone.",
  inputSchema: {
    start_date: z.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    agent_name: z.string().nullable().describe("Filtra por nome do vendedor/agente (busca parcial). Use null para todos."),
    campaign_name: z.string().nullable().describe("Filtra por campanha (busca parcial). Use null para todas."),
    direction: z.enum(["inbound", "outbound", "all"]).describe("Dire\xE7\xE3o das liga\xE7\xF5es."),
    limit: z.number().int().min(1).max(500).describe("Quantidade m\xE1xima de liga\xE7\xF5es detalhadas retornadas (ex.: 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, agent_name, campaign_name, direction, limit }, ctx) => {
    const supabase = requireUser(ctx);
    let query = supabase.from("threecplus_call_logs").select(
      "id, agent_name, agent_email, call_type, direction, phone, contact_name, campaign_name, status, qualification_name, duration_seconds, wait_seconds, acw_seconds, started_at, connected_at, ended_at"
    ).gte("started_at", toIso(start_date)).lte("started_at", toIso(end_date, true)).order("started_at", { ascending: false }).limit(limit);
    if (agent_name) query = query.ilike("agent_name", `%${agent_name}%`);
    if (campaign_name) query = query.ilike("campaign_name", `%${campaign_name}%`);
    if (direction !== "all") query = query.eq("direction", direction);
    const { data, error } = await query;
    failIf(error);
    const calls = data ?? [];
    const connected = calls.filter((c) => !!c.connected_at);
    const totalDuration = calls.reduce((acc, c) => acc + (c.duration_seconds ?? 0), 0);
    const byAgent = /* @__PURE__ */ new Map();
    for (const c of calls) {
      const key = c.agent_name ?? "Sem agente";
      const row = byAgent.get(key) ?? { ligacoes: 0, atendidas: 0, duracao_segundos: 0 };
      row.ligacoes += 1;
      if (c.connected_at) row.atendidas += 1;
      row.duracao_segundos += c.duration_seconds ?? 0;
      byAgent.set(key, row);
    }
    return jsonResult({
      periodo: { inicio: start_date, fim: end_date },
      resumo: {
        total_ligacoes: calls.length,
        atendidas: connected.length,
        taxa_atendimento_pct: calls.length ? Math.round(connected.length / calls.length * 1e3) / 10 : 0,
        tempo_total: secondsToHuman(totalDuration),
        duracao_media_segundos: connected.length ? Math.round(totalDuration / connected.length) : 0
      },
      por_vendedor: [...byAgent.entries()].map(([vendedor, v]) => ({ vendedor, ...v, tempo_total: secondsToHuman(v.duracao_segundos) })).sort((a, b) => b.ligacoes - a.ligacoes),
      ligacoes: calls,
      observacao: calls.length === limit ? `Resultado truncado em ${limit} liga\xE7\xF5es. Reduza o per\xEDodo ou filtre por vendedor para uma vis\xE3o completa.` : null
    });
  }
});

// src/lib/mcp/tools/sales-deals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var sales_deals_default = defineTool2({
  name: "sales_deals",
  title: "Neg\xF3cios do pipeline",
  description: "Lista neg\xF3cios do pipeline comercial com est\xE1gio, valor, respons\xE1vel, status (aberto/ganho/perdido) e motivo de perda, com resumo agregado.",
  inputSchema: {
    start_date: z2.string().nullable().describe("Data inicial de cria\xE7\xE3o (YYYY-MM-DD). null = sem limite."),
    end_date: z2.string().nullable().describe("Data final de cria\xE7\xE3o (YYYY-MM-DD). null = sem limite."),
    status: z2.enum(["open", "won", "lost", "all"]).describe("Status dos neg\xF3cios."),
    search: z2.string().nullable().describe("Busca parcial no t\xEDtulo ou nome do contato. null = sem busca."),
    limit: z2.number().int().min(1).max(500).describe("M\xE1ximo de neg\xF3cios retornados (ex.: 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, status, search, limit }, ctx) => {
    const supabase = requireUser(ctx);
    let query = supabase.from("deals").select(
      "id, title, status, value, entry_value, received_value, contact_name, contact_email, contact_phone, source, is_renewal, probability, expected_close_date, won_at, lost_at, lost_reason, loss_notes, stage_changed_at, created_at, updated_at, stage_id, pipeline_id, responsible_user_id, sdr_user_id, client_id, deal_stages(name), pipelines(name)"
    ).is("deleted_at", null).order("created_at", { ascending: false }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("created_at", startIso);
    if (endIso) query = query.lte("created_at", endIso);
    if (status !== "all") query = query.eq("status", status);
    if (search) query = query.or(`title.ilike.%${search}%,contact_name.ilike.%${search}%`);
    const { data, error } = await query;
    failIf(error);
    const deals = data ?? [];
    const sum = (rows) => rows.reduce((acc, d) => acc + Number(d.value ?? 0), 0);
    const won = deals.filter((d) => d.status === "won");
    const lost = deals.filter((d) => d.status === "lost");
    const byStage = /* @__PURE__ */ new Map();
    for (const d of deals) {
      const key = d.deal_stages?.name ?? "Sem est\xE1gio";
      const row = byStage.get(key) ?? { negocios: 0, valor: 0 };
      row.negocios += 1;
      row.valor += Number(d.value ?? 0);
      byStage.set(key, row);
    }
    return jsonResult({
      resumo: {
        total: deals.length,
        ganhos: won.length,
        perdidos: lost.length,
        abertos: deals.filter((d) => d.status !== "won" && d.status !== "lost").length,
        valor_total: sum(deals),
        valor_ganho: sum(won),
        taxa_conversao_pct: won.length + lost.length > 0 ? Math.round(won.length / (won.length + lost.length) * 1e3) / 10 : 0
      },
      por_estagio: [...byStage.entries()].map(([estagio, v]) => ({ estagio, ...v })),
      negocios: deals
    });
  }
});

// src/lib/mcp/tools/sales-goals-commissions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var sales_goals_commissions_default = defineTool3({
  name: "sales_goals_commissions",
  title: "Metas e comiss\xF5es",
  description: "Retorna metas comerciais do per\xEDodo e os lan\xE7amentos de comiss\xE3o por neg\xF3cio (valor, percentual, status de aprova\xE7\xE3o e pagamento).",
  inputSchema: {
    start_date: z3.string().describe("In\xEDcio do per\xEDodo (YYYY-MM-DD)."),
    end_date: z3.string().describe("Fim do per\xEDodo (YYYY-MM-DD)."),
    include_goals: z3.boolean().describe("Incluir metas de vendas do per\xEDodo."),
    include_commissions: z3.boolean().describe("Incluir lan\xE7amentos de comiss\xE3o do per\xEDodo."),
    limit: z3.number().int().min(1).max(500).describe("M\xE1ximo de registros por bloco (ex.: 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, include_goals, include_commissions, limit }, ctx) => {
    const supabase = requireUser(ctx);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    const payload = { periodo: { inicio: start_date, fim: end_date } };
    if (include_goals) {
      const { data, error } = await supabase.from("sales_goals").select("id, client_id, goal_amount, currency, period_start, period_end, created_at").gte("period_end", start_date).lte("period_start", end_date).order("period_start", { ascending: false }).limit(limit);
      failIf(error);
      const metas = data ?? [];
      payload.metas = metas;
      payload.metas_total = metas.reduce((acc, g) => acc + Number(g.goal_amount ?? 0), 0);
    }
    if (include_commissions) {
      const { data, error } = await supabase.from("commission_deal_entries").select(
        "id, deal_id, deal_title, client_name, deal_value, commission_percent, commission_total, commission_released, commission_pending, commission_status, payment_status, payment_method, approval_status, paid_at, released_at, period_id, plan_id, created_at"
      ).gte("created_at", startIso).lte("created_at", endIso).order("created_at", { ascending: false }).limit(limit);
      failIf(error);
      const entradas = data ?? [];
      payload.comissoes = entradas;
      payload.comissoes_resumo = {
        lancamentos: entradas.length,
        total: entradas.reduce((a, e) => a + Number(e.commission_total ?? 0), 0),
        liberado: entradas.reduce((a, e) => a + Number(e.commission_released ?? 0), 0),
        pendente: entradas.reduce((a, e) => a + Number(e.commission_pending ?? 0), 0),
        valor_negocios: entradas.reduce((a, e) => a + Number(e.deal_value ?? 0), 0)
      };
    }
    return jsonResult(payload);
  }
});

// src/lib/mcp/tools/zapp-conversations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^3.25.76";
var zapp_conversations_default = defineTool4({
  name: "zapp_conversations",
  title: "Conversas do RoyZapp",
  description: "Lista conversas do RoyZapp (WhatsApp) com contato, setor, \xFAltima mensagem e volume, filtrando por per\xEDodo ou busca.",
  inputSchema: {
    start_date: z4.string().nullable().describe("Data inicial da \xFAltima mensagem (YYYY-MM-DD). null = sem limite."),
    end_date: z4.string().nullable().describe("Data final da \xFAltima mensagem (YYYY-MM-DD). null = sem limite."),
    search: z4.string().nullable().describe("Busca parcial por nome do contato ou telefone. null = sem busca."),
    include_groups: z4.boolean().describe("Incluir grupos al\xE9m de conversas individuais."),
    limit: z4.number().int().min(1).max(200).describe("M\xE1ximo de conversas retornadas (ex.: 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date, search, include_groups, limit }, ctx) => {
    const supabase = requireUser(ctx);
    let query = supabase.from("zapp_conversations").select(
      "id, contact_name, phone_e164, channel, sector_id, client_id, deal_id, lead_id, is_group, unread_count, last_message_at, last_message_preview, created_at"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("last_message_at", startIso);
    if (endIso) query = query.lte("last_message_at", endIso);
    if (!include_groups) query = query.eq("is_group", false);
    if (search) query = query.or(`contact_name.ilike.%${search}%,phone_e164.ilike.%${search}%`);
    const { data, error } = await query;
    failIf(error);
    return jsonResult({ total: data?.length ?? 0, conversas: data ?? [] });
  }
});

// src/lib/mcp/tools/zapp-messages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^3.25.76";
var zapp_messages_default = defineTool5({
  name: "zapp_messages",
  title: "Mensagens de uma conversa",
  description: "Retorna as mensagens de uma conversa do RoyZapp (texto e transcri\xE7\xE3o de \xE1udio) em ordem cronol\xF3gica, para an\xE1lise de atendimento.",
  inputSchema: {
    conversation_id: z5.string().uuid().describe("ID da conversa (obtido em zapp_conversations)."),
    start_date: z5.string().nullable().describe("Data inicial (YYYY-MM-DD). null = sem limite."),
    end_date: z5.string().nullable().describe("Data final (YYYY-MM-DD). null = sem limite."),
    limit: z5.number().int().min(1).max(500).describe("M\xE1ximo de mensagens retornadas (ex.: 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id, start_date, end_date, limit }, ctx) => {
    const supabase = requireUser(ctx);
    let query = supabase.from("zapp_messages").select(
      "id, direction, content, transcription, message_type, media_type, sender_name, sender_phone, sender_user_id, delivery_status, sent_at"
    ).eq("zapp_conversation_id", conversation_id).is("deleted_at", null).order("sent_at", { ascending: true }).limit(limit);
    const startIso = toIso(start_date);
    const endIso = toIso(end_date, true);
    if (startIso) query = query.gte("sent_at", startIso);
    if (endIso) query = query.lte("sent_at", endIso);
    const { data, error } = await query;
    failIf(error);
    const msgs = data ?? [];
    return jsonResult({
      conversation_id,
      total: msgs.length,
      recebidas: msgs.filter((m) => m.direction === "inbound").length,
      enviadas: msgs.filter((m) => m.direction === "outbound").length,
      mensagens: msgs
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "mtzoavtbtqflufyccern";
var mcp_default = defineMcp({
  name: "roy-eternum",
  title: "ROY ETERNUM",
  version: "0.1.0",
  instructions: "Ferramentas de an\xE1lise comercial do ROY ETERNUM. Use `telephony_calls` para liga\xE7\xF5es da 3C Plus, `sales_deals` para o pipeline de neg\xF3cios, `sales_goals_commissions` para metas e comiss\xF5es, e `zapp_conversations` + `zapp_messages` para o atendimento no RoyZapp. Todas as ferramentas s\xE3o somente leitura e respeitam as permiss\xF5es do usu\xE1rio conectado. Datas no formato YYYY-MM-DD.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [telephony_calls_default, sales_deals_default, sales_goals_commissions_default, zapp_conversations_default, zapp_messages_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
